owner: rcpch
repo: upptime-rcpch-web-services

sites:
  - name: Check GET growth.rcpch.ac.uk responds
    url: https://growth.rcpch.ac.uk
  - name: Check GET dev.rcpch.ac.uk responds
    url: https://dev.rcpch.ac.uk
  - name: Check GET api.rcpch.ac.uk without Auth returns 401
    url: https://api.rcpch.ac.uk/v1/growth
    expectedStatusCodes:
      - 401

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime-rcpch-web-services
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: RCPCH Uptime Monitors
  introTitle: "RCPCH Digital Growth Charts Status Page"
  introMessage: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  navbar:
    - title: RCPCH Upptime GitHub repo
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
