owner: rcpch
repo: upptime-rcpch-web-services

sites:
  - name: Check GET growth.rcpch.ac.uk responds
    url: https://growth.rcpch.ac.uk
  - name: Check GET dev.rcpch.ac.uk responds
    url: https://dev.rcpch.ac.uk
  - name: Check GET api.rcpch.ac.uk without Auth returns 401
    url: https://api.rcpch.ac.uk/v1/growth
    expectedStatusCodes:
      - 401

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: RCPCH Uptime Monitors
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
